#version: "3"
version: "2"
networks:
  engine:
    driver: bridge

services:
  engine-api:
    build: '.'
    container_name: engine-api
    networks:
      - engine
    depends_on:
      - engine-bd
    links:
      - engine-bd
    ports:
      - 5000:5000
    restart: always

  engine-bd:
      image: postgres:14.1-alpine
      mem_limit: 512m
      mem_reservation: 128M
      container_name: engine-bd
      networks:
      - engine
      volumes:
        - ./docker/services/postgres/data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=bd
      ports:
        - 5432:5432
      restart: always
  
  engine-nginx:
    image: nginx:1.16-alpine
    container_name: engine-nginx
    working_dir: /application
    networks:
      - engine
    volumes:
      - ./docker/services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #- ./services/nginx/ssl:/etc/ssl
      - ./frontend/build:/application
    environment:
      - TZ=America/Belem
    ports:
      - 80:80
    restart: always