FROM python:3.9.10-alpine3.14
WORKDIR /srv
RUN pip install --upgrade pip
RUN pip install flask
RUN pip install fastapi
RUN pip install uvicorn
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0"]