#version: "3"
version: "3"
networks:
  engine:
    driver: bridge

services:
  engine-api:
    build:
      dockerfile_inline: |
        FROM python:3.9.10-alpine3.14
        WORKDIR /srv
        RUN pip install --upgrade pip
        RUN pip install flask
        RUN pip install fastapi
        RUN pip install uvicorn
        CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0"]
    container_name: engine-api
    networks:
      - engine
    volumes:
      - ./backend/src:/srv
    depends_on:
      - engine-bd
    links:
      - engine-bd
    ports:
      - 8000:8000
    restart: always

  engine-bd:
      image: postgres:14.1-alpine
      mem_limit: 512m
      mem_reservation: 128M
      container_name: engine-bd
      networks:
      - engine
      volumes:
        - ./docker/services/postgres/data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=bd
      ports:
        - 5432:5432
      restart: always
  
  engine-nginx:
    image: nginx:1.16-alpine
    container_name: engine-nginx
    working_dir: /application
    networks:
      - engine
    volumes:
      - ./docker/services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #- ./services/nginx/ssl:/etc/ssl
      - ./frontend/build:/application
    environment:
      - TZ=America/Belem
    ports:
      - 80:80
    restart: always